// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9qUTNagxWB75nEk8y1pMfkilT1m9PuM',
    appId: '1:795006129974:web:7b890cb244ea11d3004597',
    messagingSenderId: '795006129974',
    projectId: 'expense-personal',
    authDomain: 'expense-personal.firebaseapp.com',
    storageBucket: 'expense-personal.firebasestorage.app',
    measurementId: 'G-GS32CF6LGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZVORy4UcZmmud3JrHyKoHrtn1gv_Hs-A',
    appId: '1:795006129974:android:bc12f0e749bda63c004597',
    messagingSenderId: '795006129974',
    projectId: 'expense-personal',
    storageBucket: 'expense-personal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS_YeGW3xBQTrhEl1GyP4qXegO8OynvfI',
    appId: '1:795006129974:ios:97323c757674bbb0004597',
    messagingSenderId: '795006129974',
    projectId: 'expense-personal',
    storageBucket: 'expense-personal.firebasestorage.app',
    androidClientId: '795006129974-tcclps67f1evjta3rvo86ru4phqlvc26.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensePersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS_YeGW3xBQTrhEl1GyP4qXegO8OynvfI',
    appId: '1:795006129974:ios:97323c757674bbb0004597',
    messagingSenderId: '795006129974',
    projectId: 'expense-personal',
    storageBucket: 'expense-personal.firebasestorage.app',
    androidClientId: '795006129974-tcclps67f1evjta3rvo86ru4phqlvc26.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensePersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS9qUTNagxWB75nEk8y1pMfkilT1m9PuM',
    appId: '1:795006129974:web:b6a4c48dd4655849004597',
    messagingSenderId: '795006129974',
    projectId: 'expense-personal',
    authDomain: 'expense-personal.firebaseapp.com',
    storageBucket: 'expense-personal.firebasestorage.app',
    measurementId: 'G-VSEN6FDY09',
  );
}
